[variables]
    NODE_ENV = "production"
    HOSTNAME = "0.0.0.0"
    PORT = "3000"

[phases.install]
    cmds = ["yarn install --frozen-lockfile --ignore-engines"]

[phases.build]
    cmds = ["npx prisma generate", "npm run build"]

[start]
    cmd = "node .next/standalone/server.js"
